#!/usr/bin/env python3
# (autoreward) Build the registry: parse per-item entries (markdown + YAML-ish
# frontmatter) under models/entries/ and gauges/entries/ and regenerate the
# catalogs models/index.json and INDEX.md. Stdlib only - contributors just add a
# file and run `python scripts/build.py`. On first run it SEEDS entries from the
# legacy models/index.json + gauges/examples/*.json if entries/ are empty.
import json
import os
import glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def emit_frontmatter(d, body):
    lines = ["---"]
    for k, v in d.items():
        if isinstance(v, list):
            lines.append(f"{k}: [{', '.join(str(x) for x in v)}]")
        elif isinstance(v, int):
            lines.append(f"{k}: {v}")
        else:
            s = str(v).replace('"', "'")
            lines.append(f'{k}: "{s}"')
    lines.append("---")
    return "\n".join(lines) + "\n\n" + (body or "") + "\n"


def parse_frontmatter(text):
    if not text.startswith("---"):
        return {}, text
    _, fm, body = text.split("---", 2)
    d = {}
    for line in fm.strip().splitlines():
        if ":" not in line:
            continue
        k, rest = line.split(":", 1)
        k, rest = k.strip(), rest.strip()
        if rest.startswith("[") and rest.endswith("]"):
            d[k] = [x.strip().strip('"').strip("'") for x in rest[1:-1].split(",") if x.strip()]
        elif rest.lstrip("-").isdigit():
            d[k] = int(rest)
        else:
            d[k] = rest.strip('"').strip("'")
    return d, body.strip()


def seed():
    # models from legacy index.json
    mdir = os.path.join(ROOT, "models", "entries")
    os.makedirs(mdir, exist_ok=True)
    legacy = os.path.join(ROOT, "models", "index.json")
    if not glob.glob(os.path.join(mdir, "*.md")) and os.path.exists(legacy):
        for m in json.load(open(legacy)).get("models", []):
            body = (f"# {m['id']}\n\n**Use as:** {m.get('use_as','')}\n\n"
                    f"{m.get('how_to_use','')}\n")
            fm = {k: m[k] for k in ("id", "modality", "encodes", "use_as",
                                    "domains_strong", "domains_weak",
                                    "ranking_score", "ranking_basis", "ref") if k in m}
            open(os.path.join(mdir, f"{m['id']}.md"), "w", encoding="utf-8").write(emit_frontmatter(fm, body))
    # gauges from legacy examples/*.json
    gdir = os.path.join(ROOT, "gauges", "entries")
    os.makedirs(gdir, exist_ok=True)
    if not glob.glob(os.path.join(gdir, "*.md")):
        for f in glob.glob(os.path.join(ROOT, "gauges", "examples", "*.json")):
            g = json.load(open(f))
            body = f"# {g['id']}\n\n{g.get('workflow_goal','')}\n"
            open(os.path.join(gdir, f"{g['id']}.md"), "w", encoding="utf-8").write(emit_frontmatter(g, body))


def load_entries(subdir):
    out = []
    for f in sorted(glob.glob(os.path.join(ROOT, subdir, "entries", "*.md"))):
        d, _ = parse_frontmatter(open(f, encoding="utf-8").read())
        if d:
            out.append(d)
    return out


def main():
    seed()
    models = load_entries("models")
    gauges = load_entries("gauges")
    json.dump({"_comment": "GENERATED by scripts/build.py from models/entries/*.md - do not edit by hand.",
               "models": models}, open(os.path.join(ROOT, "models", "index.json"), "w"), indent=2)
    # human catalog
    lines = ["# Index (generated by scripts/build.py)\n",
             "## Gauges by domain\n", "| id | domain | tier | metric |", "|---|---|---|---|"]
    for g in sorted(gauges, key=lambda x: (x.get("domain", ""), x.get("id", ""))):
        lines.append(f"| `{g.get('id')}` | {g.get('domain')} | {g.get('tier')} | {str(g.get('metric',''))[:70]} |")
    lines += ["\n## Predicted-tier (human-response) models by modality + ranking\n",
              "| id | modality | rank | strong in | use as |", "|---|---|---|---|---|"]
    for m in sorted(models, key=lambda x: (x.get("modality", ""), -int(x.get("ranking_score", 0)))):
        lines.append(f"| `{m.get('id')}` | {m.get('modality')} | {m.get('ranking_score')} | "
                     f"{', '.join(m.get('domains_strong', [])[:3])} | {m.get('use_as','')[:30]} |")
    open(os.path.join(ROOT, "INDEX.md"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"built: {len(gauges)} gauges, {len(models)} models -> INDEX.md + models/index.json")


if __name__ == "__main__":
    main()
